name: "pylint"
description: "Run pylint over your repostiory"
author: "Daniël van Noord"
inputs:
  github-token:
    description: "Token to be used when authenticating to Github"
    required: true
  version:
    description: "The pylint version to use"
    required: false
    default: latest'
  config-file:
    description: "The location of the configuration file to use"
    required: false
    default: "none"
  arguments:
    description: "Command line arguments to pass to pylint"
    required: false
    default: "none"
  # TODO: Add support for path
  # path:
  #   description:
  #     "Path to source file or directory. If unspecified the action will determine the
  #     changes introduced in the commit or pull request."
  #   required: false
  #   default: "none"
runs:
  using: "node16"
  main: "dist/index.js"
